name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Prepare release
        id: prepare_release
        run: python scripts/prepare_release.py

      - name: Publish release (Conditional)
        if: steps.prepare_release.outputs.release == 'true'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          python scripts/commit_changes.py "Release ${{ steps.prepare_release.outputs.version }}"
          poetry build
          poetry publish
