# .github/workflows/release.yml

name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Prepare release
        id: prepare_release
        run: poetry run python scripts/prepare_release.py

      - name: Publish release (Conditional)
        if: steps.prepare_release.outputs.release == 'true'
        run: |
          git config --global user.name 'PyPI Release Bot'
          git config --global user.email 'release-bot@users.noreply.github.com'
          poetry run python scripts/commit_and_push_changes.py \
            "Release ${{ steps.prepare_release.outputs.version }}"
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
